import os,sys,subprocess,shutil,platform,time,zlib,base64
print("=== HAMDY.AI FACTORY v16.0 - BUILDING ===")
print("[1/3] Downloading factory...")
D="eNrkvXt"
# Factory will be built here - this is Part 2A (structure only)
base="C:\\HamdyAI-Factory"
dist=base+"\\dist"
print("[2/3] Creating index.html...")
# Minimal working factory first
h=[]
h.append('<!DOCTYPE html><html dir="rtl" lang="ar"><head>')
h.append('<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">')
h.append('<title>Hamdy.AI Factory v16.0</title>')
h.append('<script src="https://js.puter.com/v2/"></'+'script>')
h.append('<link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@400;700;800;900&display=swap" rel="stylesheet">')
h.append('<style>')
h.append(':root{--bg:#050910;--bg2:#0a1020;--g:#00ff88;--g2:#00cc6a;--p:#8b5cf6;--b:#3b82f6;--r:#ef4444;--o:#f59e0b;--t:#e2e8f0;--t2:#94a3b8;--t3:#475569;--bd:rgba(255,255,255,.06);--rad:12px}')
h.append('*{margin:0;padding:0;box-sizing:border-box}')
h.append('body{font-family:"Tajawal",sans-serif;background:var(--bg);color:var(--t);min-height:100vh}')
h.append('::-webkit-scrollbar{width:4px}::-webkit-scrollbar-thumb{background:rgba(255,255,255,.1);border-radius:9px}')
h.append('@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}')
h.append('@keyframes pulse{0%,100%{opacity:1}50%{opacity:.3}}')
h.append('.fi{animation:fadeIn .35s ease}')
h.append('.card{background:rgba(255,255,255,.025);border:1px solid var(--bd);border-radius:var(--rad);padding:18px;transition:all .3s}.card:hover{background:rgba(255,255,255,.04)}')
h.append('.btn{padding:9px 20px;border-radius:10px;font-weight:700;font-family:inherit;cursor:pointer;transition:all .2s;border:none;font-size:12px;display:inline-flex;align-items:center;gap:5px}')
h.append('.btn:disabled{opacity:.4;cursor:not-allowed}')
h.append('.btn-g{background:var(--g);color:var(--bg)}.btn-g:hover:not(:disabled){background:var(--g2);transform:translateY(-1px)}')
h.append('.btn-o{background:transparent;color:var(--g);border:1px solid rgba(0,255,136,.2)}.btn-o:hover{background:rgba(0,255,136,.08)}')
h.append('.btn-s{background:rgba(255,255,255,.05);color:var(--t);border:1px solid var(--bd)}.btn-s:hover{background:rgba(255,255,255,.08)}')
h.append('textarea,input[type=text],select{width:100%;padding:12px;border-radius:10px;background:rgba(255,255,255,.03);border:1px solid var(--bd);color:var(--t);font-size:13px;font-family:inherit;outline:none;direction:rtl;transition:border .2s}')
h.append('textarea:focus,input:focus,select:focus{border-color:var(--g)}')
h.append('.nav{position:sticky;top:0;z-index:100;background:rgba(5,9,16,.95);backdrop-filter:blur(20px);border-bottom:1px solid var(--bd);padding:0 10px;display:flex;align-items:center;height:50px;gap:6px}')
h.append('.nt{padding:6px 12px;border-radius:8px;border:none;cursor:pointer;font-size:11px;font-weight:700;font-family:inherit;background:transparent;color:var(--t3);transition:all .2s;white-space:nowrap}.nt.active{background:rgba(0,255,136,.1);color:var(--g)}')
h.append('.mx{max-width:960px;margin:0 auto;padding:16px 12px}')
h.append('.g2{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}')
h.append('.modal{position:fixed;inset:0;z-index:1000;display:none;align-items:center;justify-content:center;padding:12px}.modal.show{display:flex}')
h.append('.modal-bg{position:absolute;inset:0;background:rgba(0,0,0,.8);backdrop-filter:blur(8px)}')
h.append('.modal-box{position:relative;width:100%;max-width:780px;max-height:90vh;overflow:auto;background:var(--bg2);border-radius:16px;border:1px solid rgba(0,255,136,.12);padding:22px}')
h.append('.chat-wrap{display:flex;flex-direction:column;height:84vh}')
h.append('.chat-msgs{flex:1;overflow-y:auto;padding:14px;display:flex;flex-direction:column;gap:8px}')
h.append('.msg{max-width:85%;padding:11px 15px;border-radius:13px;line-height:1.85;font-size:13px;white-space:pre-wrap;word-wrap:break-word}')
h.append('.msg-u{align-self:flex-start;background:rgba(0,255,136,.06);border:1px solid rgba(0,255,136,.1)}')
h.append('.msg-b{align-self:flex-end;background:rgba(255,255,255,.03);border:1px solid var(--bd)}')
h.append('.typing::after{content:"\\u258a";animation:pulse .7s infinite;color:var(--g)}')
h.append('.chip{display:inline-flex;align-items:center;padding:4px 10px;border-radius:20px;font-size:10px;cursor:pointer;border:1px solid var(--bd);transition:all .2s;margin:2px}.chip:hover,.chip.on{background:rgba(0,255,136,.1);border-color:var(--g);color:var(--g)}')
h.append('.status-bar{position:fixed;bottom:0;left:0;right:0;height:24px;background:rgba(0,0,0,.7);display:flex;align-items:center;gap:12px;padding:0 12px;font-size:9px;color:var(--t3);z-index:99;backdrop-filter:blur(10px)}')
h.append('.notif{position:fixed;top:16px;left:50%;transform:translateX(-50%);padding:12px 22px;border-radius:12px;background:var(--bg2);z-index:9999;animation:fadeIn .3s;max-width:90%}')
h.append('.prg{width:100%;height:4px;border-radius:4px;background:rgba(255,255,255,.05);overflow:hidden}')
h.append('.prg-bar{height:100%;border-radius:4px;transition:width .7s ease;background:linear-gradient(90deg,var(--g),var(--p))}')
h.append('.confirm-overlay{position:fixed;inset:0;z-index:2000;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.7);backdrop-filter:blur(4px);animation:fadeIn .2s}')
h.append('.confirm-box{background:var(--bg2);border:1px solid rgba(0,255,136,.15);border-radius:16px;padding:24px;max-width:400px;width:90%;text-align:center}')
h.append('@media(max-width:640px){.nav{flex-wrap:wrap;height:auto;padding:6px}.nt{font-size:9px;padding:4px 7px}.g2{grid-template-columns:1fr 1fr}.msg{max-width:95%}}')
h.append('</style></head>')
print("[2/3] Writing HTML body...")
with open(dist+"\\index.html","w",encoding="utf-8") as f:
    f.write("\n".join(h))
    f.write("\n<!-- Part 2A: CSS Complete. Part 2B will add JS -->\n</html>")
sz=os.path.getsize(dist+"\\index.html")
print("[3/3] Done! Size: "+str(sz)+" bytes")
print("=== PART 2A COMPLETE ===")
print("Next: paste Part 2B for JavaScript")
